<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllCommentsForGivenGagOrderByDate(int $id){

		return $this->getEntityManager()
            		->createQuery('SELECT comment FROM AppBundle:Comment comment WHERE comment.gag =:id ORDER BY comment.date ASC')
            		->setParameter('id',$id)
            		->getResult();
	}
}
