<?php

namespace AppBundle\Repository;

/**
 * GagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllGagsByDate()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT g FROM AppBundle:Gag g ORDER BY g.lastModified ASC')
                    ->getResult();
    }

    public function findOneById(int $id)
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT g FROM AppBundle:Gag g WHERE g.id=:id')
                    ->setParameter('id', $id)
                    ->getOneOrNullResult();
    }
}
