<?php

namespace AppBundle\Repository;

/**
 * GagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GagRepository extends \Doctrine\ORM\EntityRepository
{
}
