<?php

namespace AppBundle\Repository;

/**
 * GagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GagRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
	{
		return $this->getEntityManager()
            		->createQuery(
                'SELECT g FROM AppBundle:Gag g ORDER BY g.lastModified ASC'
            )
            ->getResult();

	}
}
