<?php

namespace AppBundle\Repository;

/**
 * VoteGagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getVoteForUserAndGag($user,$gag){
		return $this->getEntityManager()
                    ->createQuery('SELECT vote FROM AppBundle:Vote vote WHERE vote.user=:user AND vote.gag=:gag')
                    ->setParameter('user',$user)
                    ->setParameter('gag',$gag)
                    ->getSingleResult();
	}
}
