<?php

namespace AppBundle\Repository;

/**
 * VoteGagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteGagRepository extends \Doctrine\ORM\EntityRepository
{
}
