app:
    path: /
    defaults: { _controller: AppBundle:Clown:index }

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

register:
    path: /register
    defaults: { _controller: AppBundle:Security:register }

editProfile:
    path: /editProfile
    defaults: { _controller: AppBundle:Security:editProfile }

logout:
    path: /logout

newGag:
    path: /newGag
    defaults: { _controller: AppBundle:Clown:newGag }

gagDetail:
    path: /Gag/{id}
    defaults: { _controller: AppBundle:Clown:gagDetail}