AppBundle\Entity\Comment:
    type: entity
    table: Comment
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        message:
            type: text
        date:
            type: datetime
    manyToOne: 
        gag:
            targetEntity: Gag
            joinColumn:
                name: gag_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

    lifecycleCallbacks: {  }
