AppBundle\Entity\Gag:
    type: entity
    table: Gag
    repositoryClass: AppBundle\Repository\GagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        lastModified:
            type: datetime
        fileName:
            type: string
            length: 255
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
    lifecycleCallbacks: {  }
