AppBundle\Entity\Vote:
    type: entity
    table: VoteGag
    repositoryClass: AppBundle\Repository\VoteGagRepository
    id:
        gag:
            associationKey: true
        user:
            associationKey: true
    fields:
        upVote:
            type: boolean
        downVote:
            type: boolean
    manyToOne: 
        gag:
            targetEntity: Gag
            inversedBy: votes
    oneToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE

    lifecycleCallbacks: {  }
