AppBundle\Entity\Vote:
    type: entity
    table: Vote
    repositoryClass: AppBundle\Repository\VoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        vote:
            type: string
            nullable: true
    manyToOne: 
        gag:
            targetEntity: Gag
            inversedBy: votes
    oneToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE

    lifecycleCallbacks: {  }
